feat: add commitlint workflow
MapColonies/shared-workflows pull request #29
Opened 2024-12-17 08:11 UTC by netanelC

2024-12-17 09:13 UTC, shimoncohen commented
Please check this out for PR title as well:
https://github.com/marketplace/actions/pull-request-linter-action
If i'm not mistaken, the current workflow doesn't check the PR title.

2024-12-17 09:16 UTC, shimoncohen requested changes

2024-12-17 09:16 UTC, shimoncohen commented on commitlint.config.mjs
Please move file to `configs` folder as done here:
https://github.com/MapColonies/shared-workflows/pull/28/files

2024-12-17 10:33 UTC, netanelC commented on commitlint.config.mjs
I was not finished :cry:

2024-12-17 11:06 UTC, shimoncohen commented on commitlint.config.mjs
Sorry about the early review 😋

2024-12-17 19:42 UTC, netanelC commented on commitlint.config.mjs
The commit config should sit on the repo itself like this

2024-12-17 20:03 UTC, shimoncohen commented on commitlint.config.mjs
Well, you removed the workflow on this commit:
https://github.com/MapColonies/shared-workflows/pull/29/commits/a5434cbd6b79a18c2719f99bb933b35499075289
This totally changes the PR meaning from adding the workflow to simply adding `commitlint`.
Why not just add the workflows and enforce them for every PR here? Because I don't want us to add files like `package.lock` to this repo, it doesn't really belong here IMO.

2024-12-17 20:09 UTC, netanelC commented on commitlint.config.mjs
I thought so too, but it is meaningless to enforce them in a workflow. That way, the commits are already pushed and the checks will just fail..
I want to prevent the wrong commit message from the beginning. Can you think of an alternative besides husky?

And about the pr-title workflow, it is not belong here so I opened a new PR

2024-12-19 19:23 UTC, netanelC commented
Won't do. As discussed, it is not good to put typescript in workflows repo

2024-12-19 19:23 UTC, closed without merging

2024-12-19 19:36 UTC, shimoncohen commented
It's important to note that we said this isn't good in the current state of the repo. We still need to add the workflows for this.