feat: add workflow for checking compatibility with postgres and postgis
MapColonies/shared-workflows pull request #31
Opened 2024-12-22 14:14 UTC by shimoncohen

2024-12-23 16:53 UTC, alex131290 approved these changes

2025-01-03 14:27 UTC, shimoncohen commented on .github/workflows/pg-compatability.yaml
> +        uses: peter-evans/find-comment@v1
Updated to the latest version.

2025-01-05 11:56 UTC, CptSchnitz requested changes

2025-01-05 11:56 UTC, CptSchnitz commented on .github/workflows/postgis-check-command.yml
1. I think each run should be a separate comment
2. test results should include commit sha
3. check if its possible to run it when asked by comment on PR by someone with permissions instead of dispatch

2025-01-05 11:56 UTC, CptSchnitz commented on .github/workflows/postgis-check-command.yml
> +        node: [20.x]
should be configurable

2025-01-05 11:56 UTC, CptSchnitz commented on .github/workflows/postgis-check-command.yml
> +        description: 'Wanted postgis versions to check'
```suggestion
        description: 'Wanted postgis docker versions to check'
```

2025-01-05 11:56 UTC, CptSchnitz commented on .github/workflows/postgis-check-command.yml
> +        required: true
can you improve the description so its easier to understand

2025-01-05 12:07 UTC, alex131290 commented on .github/workflows/postgis-check-command.yml
> +    inputs:
@shimoncohen please add the node version param

```
      node-versions:
        description: 'Node.js versions to test'
        default: 20.x
        required: false
```

2025-01-05 12:09 UTC, alex131290 commented on .github/workflows/postgis-check-command.yml
> +
```
  # Convert node-versions variable from comma-delimited string to JSON
  node_versions_to_json:
    name: Convert node-versions input to JSON
    runs-on: ubuntu-latest
    outputs:
      node_versions: ${{ steps.convert-to-json.outputs.NODE_VERSIONS }}
    steps:
      - id: convert-to-json
        run: |
          node_versions=$(echo ${{ inputs.node-versions }} | jq -R -c 'split(",")')
          echo "NODE_VERSIONS=$node_versions" >> $GITHUB_OUTPUT
```

2025-01-05 12:10 UTC, alex131290 commented on .github/workflows/postgis-check-command.yml
> +    needs: [versions_to_json, create_comment]
```
needs: [versions_to_json, node_versions_to_json, create_comment]
```

2025-01-05 12:11 UTC, alex131290 commented on .github/workflows/postgis-check-command.yml
> +        node: [20.x]
```
node: ${{ fromJSON(needs.node_versions_to_json.outputs.node_versions) }}
```

2025-01-05 12:12 UTC, alex131290 requested changes
I'd say that `node` versions should be a parameter

2025-01-05 12:17 UTC, CptSchnitz requested changes

2025-01-05 12:17 UTC, CptSchnitz commented on .github/workflows/postgis-check-command.yml
> +        run: npm run test
we should not run unit tests when checking the DB

2025-01-05 13:15 UTC, michalby24 commented on .github/workflows/postgis-check-command.yml
> +            ${{ steps.test.outcome == 'success' && ':white_check_mark:' || ':x:' }} run for `postgis/postgis:${{matrix.postgres}}`
1. Each run should be in a separate commit 
2.  This should be transferred to another job.

2025-01-05 16:02 UTC, shimoncohen commented on .github/workflows/postgis-check-command.yml
> +        node: [20.x]
Made configureable.

2025-01-05 16:03 UTC, shimoncohen commented on .github/workflows/postgis-check-command.yml
> +        required: true
Added some text. At the end this is a parameter passed from the slash-command workflow.

2025-01-05 16:03 UTC, shimoncohen commented on .github/workflows/postgis-check-command.yml
> +    inputs:
Added.

2025-01-05 16:03 UTC, shimoncohen commented on .github/workflows/postgis-check-command.yml
> +
Added.

2025-01-05 16:03 UTC, shimoncohen commented on .github/workflows/postgis-check-command.yml
> +    needs: [versions_to_json, create_comment]
Added.

2025-01-05 16:03 UTC, shimoncohen commented on .github/workflows/postgis-check-command.yml
> +        node: [20.x]
Added.

2025-01-05 16:59 UTC, shimoncohen commented on .github/workflows/postgis-check-command.yml
> +        run: npm run test
Fixed.

2025-01-05 17:01 UTC, shimoncohen commented on .github/workflows/postgis-check-command.yml
1. Fixed
2. Sadly we can't get the last `commit-sha` because of the command nature, I added an appropriate text so it will be clear enough
3. I think this is currently isn't needed and too complex

2025-01-05 17:03 UTC, shimoncohen commented on .github/workflows/postgis-check-command.yml
> +            ${{ steps.test.outcome == 'success' && ':white_check_mark:' || ':x:' }} run for `postgis/postgis:${{matrix.postgres}}`
1. Changed
2. Maybe this should be done in a future version

2025-01-05 17:14 UTC, alex131290 approved these changes

2025-01-06 09:47 UTC, CptSchnitz approved these changes

2025-01-06 13:36 UTC, netanelC approved these changes

2025-01-06 13:37 UTC, merged